apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-clients-jira-token: ""
        vault.hashicorp.com/agent-inject-template-clients-jira-token: |
          {{- with secret "transit/git/decrypt/team12-ycs-clients" "ciphertext=vault:v1:A+qCYbqPttHyUT/w21N2jWH9Edu+CYue5MrTL2ke3Nw7QsZS8piYGwWHqx2ivGoewCThHg==" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: PASSWORD_ALFA_NUMERIC
          {{ .Data.plaintext }}
          {{- end -}}
