apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients
spec:
  template:
    spec:
      containers:
        - name: clients
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: team,$(ENVIRONMENT),$(NAMESPACE),$(ENVIRONMENT)-$(NAMESPACE)
