apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-clients-jira-token: ""
        vault.hashicorp.com/agent-inject-template-clients-jira-token: |
          {{- with secret "transit/git/decrypt/team6-ycs-clients" "ciphertext=vault:v1:VcfJzwGI7PRg30P4H5FUNRhq6NfBhAFaGiH374BtBNwjmJAUZ5ky0XaxU8wGPr6ienDEoQ==" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: PASSWORD_ALFA_NUMERIC
          {{ .Data.plaintext }}
          {{- end -}}
