apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - var-ref.yaml
resources:
  - service.yaml
  - deployment.yaml
  - service-account.yaml
vars:
  - name: NAMESPACE
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: clients
    fieldref:
      fieldpath: metadata.namespace
commonLabels:
  name: clients
