apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-clients-jira-token: ""
        vault.hashicorp.com/agent-inject-template-clients-jira-token: |
          {{- with secret "transit/git/decrypt/team9-ycs-clients" "ciphertext=vault:v1:hRO0U1NLlYgf4OtTYhp30YlYnubTVrGRlt1pXqKerUcH6jWbwiFVixnqPIePZhFMQY7ysA==" "context=eW9sdC1naXQtc3RvcmFnZQo=" -}}
          type: PASSWORD_ALFA_NUMERIC
          {{ .Data.plaintext }}
          {{- end -}}
